SET CPU_TYPE=ARMv8MBL
SET CPU_VENDOR=ARM
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x00B71B00
"C:\Program Files\GNU Tools ARM Embedded\5.4 2016q3\bin\arm-none-eabi-gcc" @".\main.__i"
"C:\Program Files\GNU Tools ARM Embedded\5.4 2016q3\bin\arm-none-eabi-gcc" @".\retarget.__i"
"C:\Program Files\GNU Tools ARM Embedded\5.4 2016q3\bin\arm-none-eabi-gcc" @".\secureattrib.__i"
"C:\Program Files\GNU Tools ARM Embedded\5.4 2016q3\bin\arm-none-eabi-gcc" @".\system_tc8234.__i"
"C:\Program Files\GNU Tools ARM Embedded\5.4 2016q3\bin\arm-none-eabi-gcc" @".\tz_gcc.lnp"
